zone = []
loc_zone = 0
a = 0
input = int(input())
a = 4
b = 2
a = []
Enter = int(input("Enter : "))
start = 1
end = 100
language = ["C", "A", "M", "B", "R", "I", "D", "G", "E"]
email = []
see = []
a = 0
b = 0
flag = 0
temp = input("Enter : ")
item = ["a", "b", "c"]
cost = [300, 500, 900]
money = int(input("Enter Money : "))
buy = str(input("Enter Item : "))
number = 0
a = []
c = []
max = 0
a = int(input())
b = int(input())
v = int(input())
c = a-b
Length = 0
Length = int(v/c)